from tkinter import * 
from tkinter import ttk

root = Tk()

#Monitors Copy and paste.
entry = ttk.Entry(root)
entry.pack()
entry.bind('<<Copy>>',lambda e: print('Copy'))
entry.bind('<<Paste>>',lambda e: print('Paste'))

#Create a new event that looks for odd numbers
entry.event_add('<<OddNumber>>', '1','3','5','7','9')
entry.bind('<<OddNumber>>',lambda e: print("odd Number pressed"))

#Events can be manually generated by calling generate event. 
entry.event_generate('<<OddNumber>>')

#This will deconstruct the "Odd number event."
entry.event_delete('<<OddNumber>>')

root.mainloop()